hcloud_image: debian-10
# cx11 kleinster Server mit einer CPU f√ºr Tests
# ccx31 8 Dedicierte VCPUs 32 GB RAM
hcloud_server_type: "{{ 'cx11' if hcloud_test else 'ccx31' }}"
hcloud_server_location: nbg1
hcloud_floating_ips:
  - vhb01.meet-ipv4
  - vhb01.meet-ipv6

jitsi_meet_jvb_cfg_java_jvb_props:
   - "--subdomain=vbh01"
   - "--apis=rest"

dynamic_jitsi_scaler_turn_on:
  participants: 10
  conferences: 1
  whhm: 1175

dynamic_jitsi_scaler_turn_off:
  participants: 4
  conferences: 2


